
;;***************************************
;;***** USER PROGRAM INLUDE FILE*********
;;***************************************

;=-------------------------------
;=INCLUDE LIBRARY               - 
;=EXTERNAL REFERENCE FILE       -
;=-------------------------------
INCLUDE "..\TKS_GLOBE_VARIES.INC"
INCLUDE "..\BS83B08A_CTOUCH_V501\BS83B08A_CTOUCH_V501.AEX" 
INCLUDE "..\Ultrasonic_Atomizer_APP_V100\Ultrasonic_Atomizer_APP_V100.AEX" 












